#!/usr/bin/env python3
"""Extract the api_server route table straight from the Python source.

Routes are declared as `(METHOD, PATH, handler)` tuples and mounted via
`self._app.router.add_route(...)`, so they can be read off reliably instead of
being described by hand (or by an LLM: the agy-generated api-server-map.md
fabricated handler names and line numbers, which is why this exists).

Writes rust/analysis/api-server-routes.md. Usage:
    python3 rust/tools/extract_api_routes.py
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FILES = [
    "gateway/platforms/api_server.py",
    "gateway/platforms/api_server_runs.py",
    "gateway/platforms/api_server_room_grants.py",
    "gateway/platforms/api_server_room_dispatch.py",
]
PAT = re.compile(r'^\s*\("(GET|POST|PUT|DELETE|PATCH|HEAD|\*)",\s*"([^"]+)",\s*(self\.)?([A-Za-z_0-9]+)')


def main() -> int:
    out = ["# API server route table (verified extraction)\n"]
    out.append(
        "Generated by `rust/tools/extract_api_routes.py` directly from the Python\n"
        "source, with handler existence checked. Regenerate after touching routes.\n"
    )
    total = 0
    for rel in FILES:
        path = REPO / rel
        if not path.exists():
            continue
        src = path.read_text(encoding="utf-8")
        rows = []
        for i, line in enumerate(src.split("\n"), 1):
            m = PAT.match(line)
            if m:
                h = m.group(4)
                ok = bool(re.search(rf"def {re.escape(h)}\b", src))
                rows.append((i, m.group(1), m.group(2), h, ok))
        if not rows:
            continue
        total += len(rows)
        out.append(f"\n## `{rel}` ({len(rows)} routes)\n")
        out.append("| Method | Path | Handler | Line | Handler defined in file |")
        out.append("|---|---|---|---|---|")
        for ln, meth, p, h, ok in rows:
            out.append(f"| `{meth}` | `{p}` | `{h}` | {ln} | {'yes' if ok else 'NO'} |")
    out.append(f"\n**Total registered routes: {total}** (plus one `/p/{{profile}}` mirror each).\n")
    dest = REPO / "rust" / "analysis" / "api-server-routes.md"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {dest} ({total} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
