//! Prompt-cache key routing shared by the Responses (Codex) and Chat
//! Completions transports.
//!
//! Ports five Python functions:
//!   - `agent/transports/codex.py::_cache_scope_from_session_id`
//!   - `agent/transports/codex.py::_bounded_prompt_cache_key`
//!   - `agent/transports/codex.py::_content_cache_key`
//!   - `agent/transports/chat_completions.py::_static_prompt_instructions`
//!   - `agent/transports/chat_completions.py::_add_prompt_cache_key` (public
//!     `apply`)
//!
//! `apply` mutates SDK-shaped `api_kwargs` in place, BEFORE `extra_body` is
//! flattened onto the request, exactly as the Python transport does. The cache
//! key is a routing hint only, never a correctness boundary: two requests that
//! share a scope, system prefix, and tool set intentionally resolve to the same
//! warm-prefix bucket.
//!
//! The content hash must match CPython byte-for-byte, so the JSON serialization
//! reproduces `json.dumps(..., sort_keys=True, ensure_ascii=False,
//! separators=(",", ":"))` including float spelling and lexicographic key
//! sorting, and the tool list is stably sorted by TOP-level `name`/`type`
//! (never a nested `function.name`). See `rust/analysis/prompt-cache-claude.md`
//! for the documented limitations (unbounded ints, lone surrogates).
use crate::python_value::{decimal_digit, python_number, python_repr, python_whitespace, truthy};
use serde_json::Value;
use sha2::{Digest, Sha256};

// ---------------------------------------------------------------------------
// Public entry point (chat_completions._add_prompt_cache_key)
// ---------------------------------------------------------------------------

/// Add a content-addressed prompt cache key only for an explicitly capable
/// endpoint, mirroring `_add_prompt_cache_key`.
///
/// An explicit caller body field is authoritative: a caller-supplied
/// `prompt_cache_key` (top level or inside `extra_body`) is bounded in place to
/// the 64-char wire limit and never replaced by an autogenerated key. Both
/// locations are handled separately, and if bounding yields an empty key the
/// field is removed with no autogeneration afterwards. Caller keys are honored
/// even when `supports` is false.
pub fn apply(
    api_kwargs: &mut Value,
    messages: &[Value],
    tools: Option<&Value>,
    supports: bool,
    session_id: Option<&str>,
    cache_scope_id: Option<&str>,
) {
    let Some(obj) = api_kwargs.as_object_mut() else {
        return;
    };

    let extra_is_dict = obj.get("extra_body").map(Value::is_object).unwrap_or(false);
    let extra_has_key = extra_is_dict
        && obj["extra_body"]
            .as_object()
            .map(|m| m.contains_key("prompt_cache_key"))
            .unwrap_or(false);
    let caller_supplied = obj.contains_key("prompt_cache_key") || extra_has_key;

    if caller_supplied {
        if obj.contains_key("prompt_cache_key") {
            match bounded_prompt_cache_key(&obj["prompt_cache_key"]) {
                Some(bounded) => {
                    obj.insert("prompt_cache_key".to_string(), Value::String(bounded));
                }
                None => {
                    obj.shift_remove("prompt_cache_key");
                }
            }
        }
        if extra_has_key {
            // Read the current value immutably, bound it, then take the mutable
            // borrow: no aliasing since the bound result is owned.
            let bounded = bounded_prompt_cache_key(&obj["extra_body"]["prompt_cache_key"]);
            if let Some(extra) = obj.get_mut("extra_body").and_then(Value::as_object_mut) {
                match bounded {
                    Some(bounded) => {
                        extra.insert("prompt_cache_key".to_string(), Value::String(bounded));
                    }
                    None => {
                        extra.shift_remove("prompt_cache_key");
                    }
                }
            }
        }
        return;
    }

    if !supports {
        return;
    }

    // cache_scope_id (rotation-stable logical scope) takes precedence over the
    // physical session_id: `cache_scope_id or session_id` in Python.
    let scope_src = match cache_scope_id {
        Some(value) if !value.is_empty() => Some(value),
        _ => session_id,
    };
    let scope = cache_scope_from_session_id(scope_src);
    let instructions = static_prompt_instructions(messages);
    if let Some(cache_key) = content_cache_key(&instructions, tools, &scope) {
        obj.insert("prompt_cache_key".to_string(), Value::String(cache_key));
    }
}

// ---------------------------------------------------------------------------
// codex._cache_scope_from_session_id
// ---------------------------------------------------------------------------

/// Normalize a physical session_id into a stable logical cache scope.
///
/// Cron fires build `cron_<job_id>_<YYYYMMDD_HHMMSS>`; the trailing per-fire
/// timestamp is stripped so repeat fires of one job share a scope. Every other
/// session_id (main run, a child/subagent, a sibling child) is used unchanged.
///
/// Reproduces `re.match(r"^(cron_.+)_\d{8}_\d{6}$", str(session_id or ""))`
/// with CPython semantics: `.` never crosses a newline, `\d` matches any
/// Unicode decimal digit (not just ASCII), and `$` matches at end of string or
/// immediately before a single trailing newline.
pub fn cache_scope_from_session_id(session_id: Option<&str>) -> String {
    let sid = match session_id {
        Some(value) if !value.is_empty() => value,
        _ => "",
    };
    match match_cron_scope(sid) {
        Some(group1) => group1.to_string(),
        None => sid.to_string(),
    }
}

/// Return capture group 1 of `^(cron_.+)_\d{8}_\d{6}$` if the whole string
/// matches under CPython `re` rules, else None.
fn match_cron_scope(sid: &str) -> Option<&str> {
    if !sid.starts_with("cron_") {
        return None;
    }
    let chars: Vec<char> = sid.chars().collect();
    let len = chars.len();

    // `$` (non-MULTILINE) matches at the end, or just before one trailing "\n".
    let mut ends = Vec::with_capacity(2);
    ends.push(len);
    if len > 0 && chars[len - 1] == '\n' {
        ends.push(len - 1);
    }

    // The suffix `_\d{8}_\d{6}` is fixed at 16 chars and, because it ends at the
    // `$` anchor, is forced to the tail. Greedy `.+` therefore takes everything
    // up to that suffix, so the parse is deterministic for any given end.
    for &end in &ends {
        // cron_ (5) + at least one `.+` char (1) + suffix (16) = 22.
        if end < 22 {
            continue;
        }
        let suffix = end - 16;
        if chars[suffix] != '_' {
            continue;
        }
        if !chars[suffix + 1..suffix + 9]
            .iter()
            .all(|&c| decimal_digit(c).is_some())
        {
            continue;
        }
        if chars[suffix + 9] != '_' {
            continue;
        }
        if !chars[suffix + 10..end]
            .iter()
            .all(|&c| decimal_digit(c).is_some())
        {
            continue;
        }
        // group1 = chars[0..suffix]. The `.+` region (chars[5..suffix]) must not
        // contain a newline, since `.` never matches one.
        if chars[5..suffix].contains(&'\n') {
            continue;
        }
        // Map the char index back to a byte offset for a borrowed slice.
        let byte_end: usize = chars[..suffix].iter().map(|c| c.len_utf8()).sum();
        return Some(&sid[..byte_end]);
    }
    None
}

// ---------------------------------------------------------------------------
// codex._bounded_prompt_cache_key
// ---------------------------------------------------------------------------

/// Return a provider-safe cache key without changing session identity.
///
/// `None` for a JSON null or a value that strips to empty. Values <= 64 code
/// points pass through; longer ones collapse to `pck_<sha256[:24]>`, matching
/// `_content_cache_key`'s compact routing-key shape. `len` is measured in
/// Unicode code points, as Python `len(str)` is.
fn bounded_prompt_cache_key(value: &Value) -> Option<String> {
    if value.is_null() {
        return None;
    }
    let rendered = python_str(value);
    let key = rendered.trim_matches(python_whitespace);
    if key.is_empty() {
        return None;
    }
    if key.chars().count() <= 64 {
        return Some(key.to_string());
    }
    Some(format!("pck_{}", &sha256_hex(key.as_bytes())[..24]))
}

// ---------------------------------------------------------------------------
// codex._content_cache_key
// ---------------------------------------------------------------------------

/// Content-address the prompt cache key within a logical cache scope.
///
/// Returns `pck_<sha256[:24]>` of `scope_id \x00 instructions \x00 tools_part`,
/// or None when there is nothing static to key on. `tools_part` is the canonical
/// JSON of the tool dicts, stably sorted by TOP-level `name`/`type`. The `\x00`
/// separators reproduce the Python hash payload.
fn content_cache_key(instructions: &str, tools: Option<&Value>, scope_id: &str) -> Option<String> {
    let tools_truthy = tools.map(truthy).unwrap_or(false);
    if instructions.is_empty() && !tools_truthy {
        return None;
    }

    let mut tools_part = String::new();
    if tools_truthy {
        // Filter to dicts (isinstance(t, dict)), then stably sort by the string
        // form of `t.get("name") or t.get("type") or ""`.
        let dicts: Vec<&Value> = match tools {
            Some(Value::Array(items)) => items.iter().filter(|t| t.is_object()).collect(),
            _ => Vec::new(),
        };
        let mut keyed: Vec<(String, &Value)> =
            dicts.into_iter().map(|t| (tool_sort_key(t), t)).collect();
        keyed.sort_by(|a, b| a.0.cmp(&b.0)); // stable, code-point order == byte order
        let sorted: Vec<Value> = keyed.into_iter().map(|(_, t)| t.clone()).collect();
        tools_part = canonical_json(&Value::Array(sorted));
    }

    let content = format!("{scope_id}\0{instructions}\0{tools_part}");
    Some(format!("pck_{}", &sha256_hex(content.as_bytes())[..24]))
}

/// `str(t.get("name") or t.get("type") or "")` with Python truthiness.
fn tool_sort_key(tool: &Value) -> String {
    if let Some(name) = tool.get("name") {
        if truthy(name) {
            return python_str(name);
        }
    }
    if let Some(kind) = tool.get("type") {
        if truthy(kind) {
            return python_str(kind);
        }
    }
    String::new()
}

// ---------------------------------------------------------------------------
// chat_completions._static_prompt_instructions
// ---------------------------------------------------------------------------

/// Return the stable system/developer prefix used for cache routing.
///
/// Only a leading `system`/`developer` message is static by contract; later
/// messages are conversation state. A string content is returned verbatim;
/// anything else (including a missing content, which Python reads as None) is
/// serialized with the canonical JSON encoder, so a missing content yields the
/// literal `"null"`.
fn static_prompt_instructions(messages: &[Value]) -> String {
    let Some(first) = messages.first() else {
        return String::new();
    };
    if !first.is_object() {
        return String::new();
    }
    match first.get("role").and_then(Value::as_str) {
        Some("system") | Some("developer") => {}
        _ => return String::new(),
    }
    match first.get("content") {
        Some(Value::String(text)) => text.clone(),
        Some(content) => canonical_json(content),
        // Missing content is Python None; json.dumps(None) == "null".
        None => canonical_json(&Value::Null),
    }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Python `str(value)`: a string renders as itself; every other type matches
/// `repr(value)` for the JSON-representable types (`str(x) == repr(x)` for
/// containers, ints, floats, and bools).
fn python_str(value: &Value) -> String {
    match value {
        Value::String(text) => text.clone(),
        other => python_repr(other),
    }
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    let digest = hasher.finalize();
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Serialize a value the way CPython's
/// `json.dumps(v, sort_keys=True, ensure_ascii=False, separators=(",", ":"))`
/// does: no whitespace, object keys sorted by code point, non-ASCII emitted
/// literally, and float spelling from `repr` (via `python_number`).
fn canonical_json(value: &Value) -> String {
    let mut out = String::new();
    write_canonical(value, &mut out);
    out
}

fn write_canonical(value: &Value, out: &mut String) {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(true) => out.push_str("true"),
        Value::Bool(false) => out.push_str("false"),
        Value::Number(number) => out.push_str(&python_number(number)),
        Value::String(text) => write_json_string(text, out),
        Value::Array(items) => {
            out.push('[');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                write_canonical(item, out);
            }
            out.push(']');
        }
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort(); // str Ord is byte order, which equals code-point order.
            out.push('{');
            for (index, key) in keys.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                write_json_string(key, out);
                out.push(':');
                write_canonical(&map[*key], out);
            }
            out.push('}');
        }
    }
}

/// CPython `c_encode_basestring` (ensure_ascii=False): escape `"`, `\`, and the
/// C0 control range, with short escapes for \b \t \n \f \r; everything else,
/// including 0x7f and all non-ASCII, passes through unescaped.
fn write_json_string(text: &str, out: &mut String) {
    out.push('"');
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{08}' => out.push_str("\\b"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\u{0c}' => out.push_str("\\f"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn opt_value(value: &Value) -> Option<&Value> {
        if value.is_null() {
            None
        } else {
            Some(value)
        }
    }

    #[derive(serde::Deserialize)]
    struct Goldens {
        scope: Vec<ScopeCase>,
        bounded: Vec<BoundedCase>,
        #[serde(rename = "static")]
        static_instructions: Vec<StaticCase>,
        content: Vec<ContentCase>,
        apply: Vec<ApplyCase>,
    }

    #[derive(serde::Deserialize)]
    struct ScopeCase {
        name: String,
        session_id: Option<String>,
        expected: String,
    }

    #[derive(serde::Deserialize)]
    struct BoundedCase {
        name: String,
        value: Value,
        expected: Option<String>,
    }

    #[derive(serde::Deserialize)]
    struct StaticCase {
        name: String,
        messages: Vec<Value>,
        expected: String,
    }

    #[derive(serde::Deserialize)]
    struct ContentCase {
        name: String,
        instructions: String,
        tools: Value,
        scope_id: String,
        expected: Option<String>,
    }

    #[derive(serde::Deserialize)]
    struct ApplyCase {
        name: String,
        api_kwargs: Value,
        messages: Vec<Value>,
        tools: Value,
        supports: bool,
        session_id: Option<String>,
        cache_scope_id: Option<String>,
        expected: Value,
    }

    fn goldens() -> Goldens {
        let raw = include_str!("../../../tools/prompt-cache-goldens.json");
        serde_json::from_str(raw).expect("golden JSON parses")
    }

    #[test]
    fn scope_matches_python() {
        let g = goldens();
        assert!(!g.scope.is_empty());
        for case in &g.scope {
            let got = cache_scope_from_session_id(case.session_id.as_deref());
            assert_eq!(got, case.expected, "scope case `{}`", case.name);
        }
    }

    #[test]
    fn bounded_matches_python() {
        let g = goldens();
        assert!(!g.bounded.is_empty());
        for case in &g.bounded {
            let got = bounded_prompt_cache_key(&case.value);
            assert_eq!(got, case.expected, "bounded case `{}`", case.name);
        }
    }

    #[test]
    fn static_instructions_match_python() {
        let g = goldens();
        assert!(!g.static_instructions.is_empty());
        for case in &g.static_instructions {
            let got = static_prompt_instructions(&case.messages);
            assert_eq!(got, case.expected, "static case `{}`", case.name);
        }
    }

    #[test]
    fn content_key_matches_python() {
        let g = goldens();
        assert!(!g.content.is_empty());
        for case in &g.content {
            let got = content_cache_key(&case.instructions, opt_value(&case.tools), &case.scope_id);
            assert_eq!(got, case.expected, "content case `{}`", case.name);
        }
    }

    #[test]
    fn apply_matches_python() {
        let g = goldens();
        assert!(!g.apply.is_empty());
        for case in &g.apply {
            let mut api_kwargs = case.api_kwargs.clone();
            apply(
                &mut api_kwargs,
                &case.messages,
                opt_value(&case.tools),
                case.supports,
                case.session_id.as_deref(),
                case.cache_scope_id.as_deref(),
            );
            assert_eq!(api_kwargs, case.expected, "apply case `{}`", case.name);
        }
    }

    // ---- Focused unit tests pinning specific ported behaviors ----

    #[test]
    fn cron_timestamp_is_stripped_but_children_are_not() {
        assert_eq!(
            cache_scope_from_session_id(Some("cron_job42_20250101_120000")),
            "cron_job42"
        );
        // No main/child stripping: a normal session id passes through unchanged.
        assert_eq!(
            cache_scope_from_session_id(Some("main_abc.child_1")),
            "main_abc.child_1"
        );
        assert_eq!(cache_scope_from_session_id(None), "");
        assert_eq!(cache_scope_from_session_id(Some("")), "");
    }

    #[test]
    fn cron_end_anchor_allows_one_trailing_newline_only() {
        // `$` matches just before a single trailing newline.
        assert_eq!(
            cache_scope_from_session_id(Some("cron_x_20250101_120000\n")),
            "cron_x"
        );
        // Two trailing newlines: no match, returned unchanged.
        assert_eq!(
            cache_scope_from_session_id(Some("cron_x_20250101_120000\n\n")),
            "cron_x_20250101_120000\n\n"
        );
    }

    #[test]
    fn cron_digits_are_unicode() {
        // Arabic-Indic digits (U+0660..) count as \d in Python.
        let sid = "cron_j_\u{0660}\u{0661}\u{0662}\u{0663}\u{0664}\u{0665}\u{0666}\u{0667}_\u{0660}\u{0661}\u{0662}\u{0663}\u{0664}\u{0665}";
        assert_eq!(cache_scope_from_session_id(Some(sid)), "cron_j");
    }

    #[test]
    fn bounded_over_length_hashes_by_code_points() {
        let key = "a".repeat(64);
        assert_eq!(bounded_prompt_cache_key(&json!(key)), Some(key.clone()));
        let long = "a".repeat(65);
        let bounded = bounded_prompt_cache_key(&json!(long)).unwrap();
        assert!(bounded.starts_with("pck_"));
        assert_eq!(bounded.len(), 4 + 24);
    }

    #[test]
    fn bounded_none_and_empty() {
        assert_eq!(bounded_prompt_cache_key(&Value::Null), None);
        assert_eq!(bounded_prompt_cache_key(&json!("   ")), None);
        assert_eq!(
            bounded_prompt_cache_key(&json!(false)),
            Some("False".into())
        );
    }

    #[test]
    fn content_sorts_tools_by_top_level_name_not_nested() {
        // Two tools whose nested function.name ordering is the reverse of their
        // top-level name ordering: the top-level name decides the hash input.
        let tools = json!([
            {"name": "b", "function": {"name": "a"}},
            {"name": "a", "function": {"name": "b"}},
        ]);
        let reordered = json!([
            {"name": "a", "function": {"name": "b"}},
            {"name": "b", "function": {"name": "a"}},
        ]);
        let one = content_cache_key("", Some(&tools), "");
        let two = content_cache_key("", Some(&reordered), "");
        assert!(one.is_some());
        assert_eq!(one, two, "sorting must make insertion order irrelevant");
    }

    #[test]
    fn content_none_when_nothing_static() {
        assert_eq!(content_cache_key("", None, ""), None);
        assert_eq!(content_cache_key("", Some(&json!([])), ""), None);
        // Non-empty tool list of non-dicts is still truthy, so it keys.
        assert!(content_cache_key("", Some(&json!(["x"])), "").is_some());
    }

    #[test]
    fn apply_bounds_caller_key_even_when_unsupported() {
        let long = "z".repeat(100);
        let mut kwargs = json!({ "prompt_cache_key": long });
        apply(&mut kwargs, &[], None, false, None, None);
        let got = kwargs["prompt_cache_key"].as_str().unwrap();
        assert!(got.starts_with("pck_"));
        assert_eq!(got.len(), 28);
    }

    #[test]
    fn apply_empty_caller_key_is_removed_not_regenerated() {
        let mut kwargs = json!({ "prompt_cache_key": "   " });
        let messages = vec![json!({"role": "system", "content": "you are helpful"})];
        // supports=true, but an explicit-then-emptied key must not autogenerate.
        apply(&mut kwargs, &messages, None, true, Some("s1"), None);
        assert_eq!(kwargs.get("prompt_cache_key"), None);
    }

    #[test]
    fn apply_bounds_extra_body_key_separately() {
        let long = "q".repeat(100);
        let mut kwargs = json!({ "extra_body": { "prompt_cache_key": long, "keep": 1 } });
        apply(&mut kwargs, &[], None, true, None, None);
        let extra = kwargs["extra_body"].as_object().unwrap();
        assert!(extra["prompt_cache_key"]
            .as_str()
            .unwrap()
            .starts_with("pck_"));
        assert_eq!(extra["keep"], json!(1));
        // No top-level key was added.
        assert!(!kwargs.as_object().unwrap().contains_key("prompt_cache_key"));
    }

    #[test]
    fn apply_autogenerates_for_supported_endpoint() {
        let mut kwargs = json!({});
        let messages = vec![json!({"role": "system", "content": "sys prefix"})];
        apply(
            &mut kwargs,
            &messages,
            None,
            true,
            Some("cron_j_20250101_120000"),
            None,
        );
        let key = kwargs["prompt_cache_key"].as_str().unwrap();
        assert!(key.starts_with("pck_"));
        // cache_scope_id precedence: passing it overrides the physical session.
        let mut kwargs2 = json!({});
        apply(
            &mut kwargs2,
            &messages,
            None,
            true,
            Some("other"),
            Some("cron_j_20250101_999999"),
        );
        // Both cron ids strip to `cron_j`, so keys match.
        assert_eq!(kwargs["prompt_cache_key"], kwargs2["prompt_cache_key"]);
    }

    #[test]
    fn apply_unsupported_without_caller_key_does_nothing() {
        let mut kwargs = json!({"model": "x"});
        let messages = vec![json!({"role": "system", "content": "sys"})];
        apply(&mut kwargs, &messages, None, false, Some("s1"), None);
        assert_eq!(kwargs, json!({"model": "x"}));
    }

    #[test]
    fn static_instructions_missing_content_is_null_literal() {
        let messages = vec![json!({"role": "system"})];
        assert_eq!(static_prompt_instructions(&messages), "null");
    }

    #[test]
    fn canonical_json_matches_python_shape() {
        // Sorted keys, no spaces, float repr spelling, non-ascii literal.
        assert_eq!(
            canonical_json(&json!({"b": 1, "a": [1.5, "\u{00e9}"]})),
            "{\"a\":[1.5,\"\u{00e9}\"],\"b\":1}"
        );
    }
}
